### ISSUE TITLE
Add margin and format Avatar component in the NavBar

### ISSUE THREAD

**Issue by fliptrail** [ai-economy-simulator/ecosim-client#1]
Avatar component in the top right is not formatted well as compared to the logo. It should be formatted similarly. 

![image](https://github.com/ai-economy-simulator/ecosim-client/assets/40834245/22112850-f2b1-4ca3-815e-67fb13e35520)

**Comment by MohammedDhange** [comment]
Can you assign this to me, I have raised a PR for the same
https://github.com/ai-economy-simulator/ecosim-client/pull/6

**Comment by fliptrail** [comment]
Thank you for the contribution. Please follow the coding style used in the logo on the left side.

**Comment by MD-19** [comment]
Done, here: https://github.com/ai-economy-simulator/ecosim-client/pull/8
