### ISSUE TITLE
Update Image when clicking on tablist on the carousel

### ISSUE THREAD

**Issue by fliptrail** [ai-economy-simulator/ecosim-client#13]
When we click on a tab in the tablist (on the carousel on the landing page), the image does not update. It should get updated. 

![image](https://github.com/ai-economy-simulator/ecosim-client/assets/40834245/985e594e-3f89-46dd-a931-898d25ce7d8c)

**Comment by coldrohak** [comment]
@fliptrail i can work on this

**Comment by fliptrail** [comment]
@coldrohak I've assigned it to you.

**Comment by Tashuuuu** [comment]
Can I work on it?

**Comment by fliptrail** [comment]
@Tashuuuu, coldrohak is already working on this. You can select some other one if you're interested.
