### ISSUE TITLE
The carousel is overflowing on mobile devices.

### ISSUE THREAD

**Issue by Ayusht777** [ai-economy-simulator/ecosim-client#20]
on Smaller screen the carousel is overflowing on right and left part of the screen
![image](https://github.com/ai-economy-simulator/ecosim-client/assets/106388215/811063cb-cddb-44eb-85c2-83d9bbe8cccd)

**Comment by fliptrail** [comment]
You can take this up. I'll assign it to you @Ayusht777 .
